server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend:8081/api/;
  }

  location /v3/ {
    proxy_pass http://backend:8081/v3/;
  }

  location /swagger-ui/ {
    proxy_pass http://backend:8081/swagger-ui/;
  }

  location / {
    try_files $uri /index.html;
  }
}
